# Generated by Django 3.1.2 on 2020-10-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201025_1401'),
        ('rooms', '0003_auto_20201025_1250'),
    ]

    operations = [
    ]
