# Generated by Django 3.1.2 on 2020-10-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0004_auto_20201024_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.CharField(default='https://res.cloudinary.com/dmhj1vjdf/image/upload/v1603705159/volunteers/fg5afp4hagsrz2fgkbwd.png', max_length=300),
        ),
    ]
