# Generated by Django 3.1.2 on 2020-10-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='room',
            new_name='room_id',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='message',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='user_id',
        ),
    ]
