# Generated by Django 3.1.2 on 2020-10-27 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('users', models.ManyToManyField(blank=True, related_name='user_shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
