# Generated by Django 3.1.2 on 2020-10-22 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='volunteers',
        ),
        migrations.AddField(
            model_name='campaign',
            name='conf_volunteers',
            field=models.ManyToManyField(blank=True, related_name='conf_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='pend_volunteers',
            field=models.ManyToManyField(blank=True, related_name='pend_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
