# Generated by Django 3.1.2 on 2020-10-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20201022_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='latitude',
            field=models.CharField(default='lat not provided', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='longitude',
            field=models.CharField(default='long not provided', max_length=20),
            preserve_default=False,
        ),
    ]
