# Generated by Django 3.1.2 on 2020-10-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_auto_20201023_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='skills',
        ),
    ]
