# Generated by Django 3.1.2 on 2020-10-25 14:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0005_auto_20201025_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='coordinators',
            field=models.ManyToManyField(blank=True, related_name='coord_campaigns', to=settings.AUTH_USER_MODEL),
        ),
    ]
