# Generated by Django 3.1.2 on 2021-01-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_auto_20201029_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='banner_image',
            field=models.CharField(default='https://mondrian.mashable.com/lead-img-anti-racist-curriculum.jpg', max_length=512),
        ),
    ]
