# Generated by Django 3.1.2 on 2020-10-24 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaign_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_auto_20201024_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='campaign_skills', to='campaigns.Campaign'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
